---
- name: Block a malicious IP using iptables
  hosts: ubuntu_host
  become: yes
  vars:
    target_ip: "192.168.1.11"

  tasks:
    - name: Kiểm tra rule đã tồn tại chưa
      ansible.builtin.command: >
        iptables -C INPUT -s {{ target_ip }} -j DROP
      register: check_rule
      failed_when: false

    - name: Thêm rule nếu chưa tồn tại
      ansible.builtin.command: >
        iptables -A INPUT -s {{ target_ip }} -j DROP
      when: check_rule.rc != 0

    - name: Lưu iptables vào file
      ansible.builtin.command: iptables-save
      register: iptables_rules

    - name: Ghi file rules.v4
      copy:
        content: "{{ iptables_rules.stdout }}"
        dest: /etc/iptables/rules.v4



