- name: Manage UFW rules
  hosts: 192.168.3.82
  gather_facts: false
  become: true
  become_method: sudo
  become_user: root
  tasks:
    - name: Debug all variables
      debug:
        msg: "All variables: {{ vars | to_json }}"
      delegate_to: 192.168.3.82

    - name: Debug data variable
      debug:
        msg: "Data variable: {{ data | default('not defined') }}"
      delegate_to: 192.168.3.82

    - name: Block IP using UFW
      ufw:
        rule: deny
        from_ip: "{{ data | default('') }}"
      when: data | length > 0
      delegate_to: 192.168.3.82

    - name: Debug UFW status
      command: ufw status
      register: ufw_status
      changed_when: false
      delegate_to: 192.168.3.82

    - name: Display UFW status
      debug:
        msg: "UFW status: {{ ufw_status.stdout_lines }}"
      delegate_to: 192.168.3.82
